#!/bin/env python3

# Copyright 2015  Malcolm Inglis <http://minglis.id.au/>


import sys
from argparse import ArgumentParser, ArgumentTypeError
from urllib.parse import urlparse
from urllib.request import urlopen
from html.parser import HTMLParser
from contextlib import closing


def main():
    args = parse_args(sys.argv[1:])
    title = title_from_url(args.url)
    print(title)


def parse_args(raw_args):
    return make_parser().parse_args(raw_args)


def make_parser():
    parser = ArgumentParser(description='Opens the given URL of a HTML '
                                        'document, and prints its title, if '
                                        'any.')
    parser.add_argument('url', help='The URL of the HTML document.')
    return parser


def title_from_url(url):
    with closing(urlopen(url)) as response:
        return extract_title(response.read().decode(errors='replace'))


def extract_title(htmls):
    parser = HTMLTitleExtractor()
    parser.feed(htmls)
    return parser.title


class HTMLTitleExtractor(HTMLParser):
    def __init__(self, *args, **kwargs):
        self.in_title = False
        self.title = ''
        super().__init__(*args, **kwargs)

    def handle_starttag(self, tag, attrs):
        self.in_title = (tag == 'title')

    def handle_endtag(self, tag):
        if tag == 'title':
            self.in_title = False

    def handle_data(self, data):
        if self.in_title:
            self.title += data


if __name__ == '__main__':
    main()

